// Generated by CoffeeScript 1.3.3
(function() {

  describe("UseCase", function() {
    it("initializes database", function() {
      console.log("fal");
      return useCase.init();
    });
    it("shows home page", function() {
      return expect(true).toEqual(true);
    });
    it("shows all categories", function() {
      return expect(true).toEqual(true);
    });
    it("shows single category", function() {
      return expect(true).toEqual(true);
    });
    it("shows single product", function() {
      return expect(true).toEqual(true);
    });
    it("shows buyers cart", function() {
      return expect(true).toEqual(true);
    });
    it("updates the small cart", function() {
      return expect(true).toEqual(true);
    });
    it("add products to the cart", function() {
      return expect(true).toEqual(true);
    });
    it("removes product from the cart", function() {
      return expect(true).toEqual(true);
    });
    it("shows form for buyers personal data if buyer is new", function() {
      return expect(true).toEqual(true);
    });
    it("saves buyers personal data", function() {
      return expect(true).toEqual(true);
    });
    it("confirms an order", function() {
      return expect(true).toEqual(true);
    });
    return it("initializes database", function() {
      return expect(true).toEqual(true);
    });
  });

}).call(this);
