# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: utf8
  database: storeapp_development
  pool: 5
  username: jedrek
  password: 

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost
  #port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: storeapp_test
  pool: 5
  username: jedrek
  password: 

production:
  adapter: postgresql
  encoding: utf8
  database: storeApp_production
  pool: 5 