development:
  adapter: postgresql
  encoding: utf8
  database: storeapp_development
  pool: 5
  username: jedrek
  password: 

test:
  adapter: postgresql
  encoding: utf8
  database: storeapp_test
  pool: 5
  username: jedrek
  password: 

production:
  adapter: postgresql
  encoding: utf8
  database: storeapp_production
  pool: 5 
